# use this compose with sudo !!!
name: koroz
services:
    unbound:
        container_name: my-unbound
        ports:
            - 53533:53/tcp
            - 53533:53/udp
        restart: unless-stopped
        volumes:
            - ./unbound_server.key:/opt/unbound/etc/unbound/unbound_server.key
            - ./unbound_server.pem:/opt/unbound/etc/unbound/unbound_server.pem
            - ./unbound_control.key:/opt/unbound/etc/unbound/unbound_control.key
            - ./unbound_control.pem:/opt/unbound/etc/unbound/unbound_control.pem
            - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
        image: mvance/unbound:latest
        post_start:
          - command: sh -c 'apt update && apt install dnsutils -y'
            user: root
    postgresml:
        stdin_open: true
        tty: true
        volumes:
            - postgresml_data:/var/lib/postgresql
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=dns
        ports:
            - 5432:5432
            - 8000:8000
        image: ghcr.io/postgresml/postgresml:2.9.3
        command: sudo -u postgresml psql -d postgresml
volumes:
    postgresml_data:
        external: true
        name: postgresml_data
